{% set name = "pygobject" %}
{% set version = "3.30.4" %}
{% set majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set sha256 = "2dc1a1a444b82955e65b81c2a2511ecf8032404beba4ef1d48144168f2f64c43" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/pygobject/{{ majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - macos-tests.patch
    - meson-rpaths.patch  # [linux]

build:
  number: 1000
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - m2-msys2-runtime  # [win]
    - ninja
    - {{posix}}patch
    - {{native}}pkg-config
  host:
    - meson
    - flake8  # for testing during the build
    - glib
    - python
    - pycairo
    - gobject-introspection 1.*
    - libffi
    - pytest
  run:
    - glib
    - python
    - pycairo
    - gobject-introspection 1.*
    - libiconv  # on Windows we seem to need the conda-forge version here (see #15)
    - libffi

test:
  imports:
    - gi
    - gi.repository.GLib
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://pygobject.readthedocs.io
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING
  summary: 'Python bindings for GObject Introspection'

  description: |
    PyGObject is a Python package which provides bindings for GObject based libraries
    such as GTK+, GStreamer, WebKitGTK+, GLib, GIO and many more.

  doc_url: https://pygobject.readthedocs.io
  dev_url: https://git.gnome.org/browse/pygobject

extra:
  recipe-maintainers:
    - pkgw
    - sebastian-luna-valero
