{% set name = "pygobject" %}
{% set version = "3.28.0" %}
{% set majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set sha256 = "42b47b261b45aedfc77e02e3c90a01cd74d6f86c3273c1860a054d531d606e5a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/pygobject/{{ majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - make 4.2.*
    - libtool 2.4.*
    - pkg-config 0.29.*
    - pytest
    - glib 2.55.*
    - python
    - pycairo 1.13.*
    - gobject-introspection 1.55.*
    - libffi 3.2.*
  run:
    - glib 2.55.*
    - python
    - pycairo 1.13.*
    - gobject-introspection 1.55.*
    - libffi 3.2.*

test:
  imports:
    - gi
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://pygobject.readthedocs.io
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING
  summary: 'Python bindings for GObject Introspection'

  description: |
    PyGObject is a Python package which provides bindings for GObject based libraries
    such as GTK+, GStreamer, WebKitGTK+, GLib, GIO and many more.

  doc_url: https://pygobject.readthedocs.io
  dev_url: https://git.gnome.org/browse/pygobject

extra:
  recipe-maintainers:
    - pkgw
    - sebastian-luna-valero
