{% set name = "pygobject" %}
{% set version = "3.28.3" %}
{% set majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set sha256 = "3dd3e21015d06e00482ea665fc1733b77e754a6ab656a5db5d7f7bfaf31ad0b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/pygobject/{{ majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1001
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - libtool
    - pkg-config
  host:
    - glib
    - python
    - pycairo
    - gobject-introspection 1.*
    - libffi
    - pytest
  run:
    - glib
    - python
    - pycairo
    - gobject-introspection 1.*
    - libffi

test:
  imports:
    - gi
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://pygobject.readthedocs.io
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING
  summary: 'Python bindings for GObject Introspection'

  description: |
    PyGObject is a Python package which provides bindings for GObject based libraries
    such as GTK+, GStreamer, WebKitGTK+, GLib, GIO and many more.

  doc_url: https://pygobject.readthedocs.io
  dev_url: https://git.gnome.org/browse/pygobject

extra:
  recipe-maintainers:
    - pkgw
    - sebastian-luna-valero
