appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NUnYyQ2/p7QYw1quXrGca9j8XDcHMRp8KbEpZx75FXJTUIna0gAdO3pOt33Fg7RFw056pQbFWBPxmL6j8klgmx4NkM+Tjj12DI3i4ndXmG+U/s1aVxqj2H/tIbY1StoPoxiuTxN4AuWTW65u9OLISBJi23hKoPkEeqp8xswuab/X1HrR5RiEajBeVTCz9zSHtAIS49qUI/KoN9i3PF0gJZBaJk82YRVwj0PJbJTMlDUw6E54SaMqpy7biXHacXRBgerV6QOuiNdYRzAP/yFeqEwrNOF+xbxh+WS+ixkFX5NseWzs7DfBCAcNLnuP/W/V16Wb3p8VnX6vd1IiYHRcHqEXBGuHjirk6urbGAnUjzE8vlF3O4eLhYuCyfDw8hfzKH+hvsVHxflO2N4cxLiBUNRgKwC1pcoAdfxWi2hRM22cjs+OPXdCRRudmIc8HO0JiMKs6svpU38dVhpmQV9qRl68YQ1t0o7beOk4qw2r44WBVUqmx9V8m3fpBYt3dz61P3OI9yR2bfZXBR/G1nVa/091NFNRQml37aek5HD5UeyUXhsXTXRWzhLJbcNgQRxEULFjbKpqdcygiuX7YAA3GQ867koRdXwUY4UWVenebgcO66Y3Oz6Tv4/eK88iYyOsMAPywNy4U1hsUDxcjE5/IQG2R0qlOB7cRKb7pbqFywA=}
provider:
  win: azure
