travis:
  secure:
    BINSTAR_TOKEN: YAIXr1xSxgBcY28VE0SwGu1sSwOyyEtEWsozqbC8EOlT7Mox8vgk+V8Gq8/j1zX+APXZhqJeDWpA9R2fTg6vubgHiEc7LWvqiUFwu3w8t97FVkE1eZzIo2Re5M81DDEvAmD+r2KxEunUpHxUxp063D2nss+vc2xwsIIEemRQTxX05lIrG+vKg9WSxz4dNXh05oH0TQr4BklZwXZkl9TKEnrFE2017/smhNcudjAOdjH5HAn4YMHNMadIZSSGxiyRTJ7tjArt1v7pf/jLNf+yR5FaT0aA6FGe+fPEkKLvJ0/FNjxqVQLpVIWXd/4700DBUFQGjKBunvdLOmEJRszBb6ByNcjUdYeMGKm+DygFcLn1iyPUPmESMaoIY0aYOww8ao0d5qTiibFeEgIN3zB2TKTHNt8T4ge4jySf9CR0KOVpnpAMNLCE9SjYftPu21bbQKjRjqhJkCpVhId0bOkUj2wY5HgzCngtDvGwexEbR1dWcMYfG+UeG6GCmn7CFEHe6aT7k1MEPRBTQyUGqcAHScC2+dJCv5uTEMzq4gWFZWR7+D4OVLaNls79dZ0m4Fcepkq1aaHvP4mWkmJiKc3zRJgA0mB1AWu2yKSf/x+IoHNqoEFMcd0dfYda0XkbcOmTgRQFuZER+yRaSvLQhw6BnxffylbGXoNFdCLAlZZRFC0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
