travis:
  secure:
    BINSTAR_TOKEN: ZF+ptBQocH1VBJJuGe+pCC5ef+fEBZR+i9fL6jOYnuO3CtHoTfp0ytzy8dLPSgZeIIv1aZyIspZRZaJL37mQc1wWVWxvH2GfVJZvrxuDPPSd8jtIRe5n+lpipYbC/W18spUTio4K/dzdJe1Wj9R8hvqHhkB1mbu8GULZ4B4LXNg66nfHavcZBuubGkhfZhL/RClaybz9m04okA+rp4nvtLy49eJNrD6+mZ2hEnIWsi/fMYzS0ly5Z/Ptv6+FGjXKZfzx7QigcH1dtJFDSKy1T5+jb4cPuGUMywMpGzBrxpz9d6HMcCGUa8yAWgHI9AChZf1Op21pbobSrViDMvu1dc8xaNblJBQz2tKLq1t3stB+OFFYD2Yk4M1tnsbKb0n81VyKxU/tEt//9xBXFFdWWVzDPoAGqWwpnVdjiVx7WJBep3jlCuW5b/G+Y9uRt7E25xYRP0i7S4B9MqRCvd7z8+D0dJ1F1/DkBr9Kxgm86dnZATJ3APWkwcZAZTIS9XCA2dpA6bYXqJZZGNkewoU96nNvt/xQgM9gSSLSmViqiODqWt1X0RsG8qiHhCnvlIFst9vsmqcSbnL0FmJ+maXCTfMSAZ3LJreO1QxTLX+uS4b8x/Goj1EJDkuh933Ts7YeTpO+t7OD+Bmk0WOuZHt24A/WmcNg02Az+VPn3pctHdw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
